---
new_page_extension: md
auto_deploy: true
admin_path: "/admin/"
webhook_url: 
sections:
- type: jekyll-pages
  label: Pages
  create: all
- type: jekyll-posts
  label: Stories
  create: all
  templates:
  - stories
- type: document
  path: _data/tags.yml
  label: Tags
- type: heading
  label: Members & Organizations
- type: document
  path: _data/principles_networks.yml
  label: 'DoGP: Networks'
- type: document
  path: _data/principles_organizations.yaml
  label: 'DoGP: Organizations'
- type: document
  path: _data/regional_networks.yml
  label: Regional Networks
- type: directory
  path: _members
  label: Members
  create: documents
  match: "**/*"
  templates:
  - members
- type: heading
  label: Translations
- type: document
  path: _data/en/strings.yaml
  label: English
- type: document
  path: _data/es/strings.yaml
  label: Spanish
- type: document
  path: _data/fr/strings.yaml
  label: French
- type: document
  path: _data/ar/strings.yaml
  label: Arabic
- type: document
  path: _data/ru/strings.yaml
  label: Russian
upload_dir: gndem
public_path: https://res.cloudinary.com/gndem/image/upload
front_matter_path: https://res.cloudinary.com/gndem/image/upload
use_front_matter_path: true
file_template: ":filename:"
instant_preview: 
build:
  preview_env:
  - JEKYLL_ENV=staging
  preview_output_directory: _site
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: bundle exec jekyll serve --drafts --unpublished --future
    --port 8080 --host 0.0.0.0 -d _site
  publish_command: bundle exec jekyll build -d _site
  publish_env:
  - JEKYLL_ENV=production
  output_directory: _site
  preview_command: bundle exec jekyll build --drafts --unpublished --future -d _site
